"""initial_schema"""
from alembic import op
import sqlalchemy as sa

revision = '744511298da7'
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('otp_challenges',
    sa.Column('phone', sa.String(length=16), nullable=False),
    sa.Column('code_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('consumed', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_otp_challenges_phone'), 'otp_challenges', ['phone'], unique=False)
    op.create_table('rate_limits',
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('resets_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('societies',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('address', sa.Text(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('phone', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('avatar_id', sa.String(length=36), nullable=True),
    sa.Column('preferences', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone')
    )
    op.create_table('amenities',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('icon', sa.String(length=40), nullable=False),
    sa.Column('opens', sa.Integer(), nullable=False),
    sa.Column('closes', sa.Integer(), nullable=False),
    sa.Column('fee', sa.Integer(), nullable=False),
    sa.Column('cancel_hours', sa.Integer(), nullable=False),
    sa.Column('society_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['society_id'], ['societies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_amenities_society_id'), 'amenities', ['society_id'], unique=False)
    op.create_table('buildings',
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('society_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['society_id'], ['societies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('society_id', 'name')
    )
    op.create_index(op.f('ix_buildings_society_id'), 'buildings', ['society_id'], unique=False)
    op.create_table('devices',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('platform', sa.String(length=10), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_index(op.f('ix_devices_user_id'), 'devices', ['user_id'], unique=False)
    op.create_table('directory',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=16), nullable=False),
    sa.Column('category', sa.String(length=40), nullable=False),
    sa.Column('society_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['society_id'], ['societies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_directory_society_id'), 'directory', ['society_id'], unique=False)
    op.create_table('documents',
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('category', sa.String(length=60), nullable=False),
    sa.Column('storage_key', sa.String(length=300), nullable=False),
    sa.Column('filename', sa.String(length=200), nullable=False),
    sa.Column('content_type', sa.String(length=80), nullable=False),
    sa.Column('owners_only', sa.Boolean(), nullable=False),
    sa.Column('society_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['society_id'], ['societies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_society_id'), 'documents', ['society_id'], unique=False)
    op.create_table('notices',
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=40), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('attachments', sa.JSON(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('society_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['society_id'], ['societies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notices_society_id'), 'notices', ['society_id'], unique=False)
    op.create_table('notifications',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('body', sa.String(length=500), nullable=False),
    sa.Column('category', sa.String(length=30), nullable=False),
    sa.Column('route', sa.String(length=200), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('society_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['society_id'], ['societies.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_society_id'), 'notifications', ['society_id'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('family', sa.String(length=36), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index(op.f('ix_refresh_tokens_family'), 'refresh_tokens', ['family'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('units',
    sa.Column('building_id', sa.String(length=36), nullable=False),
    sa.Column('number', sa.String(length=20), nullable=False),
    sa.Column('society_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['building_id'], ['buildings.id'], ),
    sa.ForeignKeyConstraint(['society_id'], ['societies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('building_id', 'number')
    )
    op.create_index(op.f('ix_units_society_id'), 'units', ['society_id'], unique=False)
    op.create_table('bills',
    sa.Column('period', sa.String(length=80), nullable=False),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('outstanding', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('unit_id', sa.String(length=36), nullable=False),
    sa.Column('society_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('amount > 0 AND outstanding >= 0 AND outstanding <= amount'),
    sa.ForeignKeyConstraint(['society_id'], ['societies.id'], ),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bills_society_id'), 'bills', ['society_id'], unique=False)
    op.create_index(op.f('ix_bills_unit_id'), 'bills', ['unit_id'], unique=False)
    op.create_table('bookings',
    sa.Column('amenity_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('start_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('fee', sa.Integer(), nullable=False),
    sa.Column('unit_id', sa.String(length=36), nullable=False),
    sa.Column('society_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('end_at > start_at'),
    sa.ForeignKeyConstraint(['amenity_id'], ['amenities.id'], ),
    sa.ForeignKeyConstraint(['society_id'], ['societies.id'], ),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_booking_overlap', 'bookings', ['amenity_id', 'start_at', 'end_at'], unique=False)
    op.create_index(op.f('ix_bookings_amenity_id'), 'bookings', ['amenity_id'], unique=False)
    op.create_index(op.f('ix_bookings_society_id'), 'bookings', ['society_id'], unique=False)
    op.create_index(op.f('ix_bookings_unit_id'), 'bookings', ['unit_id'], unique=False)
    op.create_table('complaints',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=40), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('attachments', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('assigned_to', sa.String(length=100), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('unit_id', sa.String(length=36), nullable=False),
    sa.Column('society_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['society_id'], ['societies.id'], ),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_complaints_society_id'), 'complaints', ['society_id'], unique=False)
    op.create_index(op.f('ix_complaints_unit_id'), 'complaints', ['unit_id'], unique=False)
    op.create_table('domestic_help',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('photo_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('unit_id', sa.String(length=36), nullable=False),
    sa.Column('society_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['society_id'], ['societies.id'], ),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_domestic_help_society_id'), 'domestic_help', ['society_id'], unique=False)
    op.create_index(op.f('ix_domestic_help_unit_id'), 'domestic_help', ['unit_id'], unique=False)
    op.create_table('emergency_alerts',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('unit_id', sa.String(length=36), nullable=False),
    sa.Column('society_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['society_id'], ['societies.id'], ),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_emergency_alerts_society_id'), 'emergency_alerts', ['society_id'], unique=False)
    op.create_index(op.f('ix_emergency_alerts_unit_id'), 'emergency_alerts', ['unit_id'], unique=False)
    op.create_table('family_members',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=16), nullable=False),
    sa.Column('relationship', sa.String(length=40), nullable=False),
    sa.Column('app_access', sa.Boolean(), nullable=False),
    sa.Column('unit_id', sa.String(length=36), nullable=False),
    sa.Column('society_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['society_id'], ['societies.id'], ),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('unit_id', 'phone')
    )
    op.create_index(op.f('ix_family_members_society_id'), 'family_members', ['society_id'], unique=False)
    op.create_index(op.f('ix_family_members_unit_id'), 'family_members', ['unit_id'], unique=False)
    op.create_table('invitations',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=16), nullable=False),
    sa.Column('start_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('vehicle_number', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.String(length=500), nullable=False),
    sa.Column('pin', sa.String(length=6), nullable=False),
    sa.Column('qr_token', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('unit_id', sa.String(length=36), nullable=False),
    sa.Column('society_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('end_at > start_at'),
    sa.ForeignKeyConstraint(['society_id'], ['societies.id'], ),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pin'),
    sa.UniqueConstraint('qr_token')
    )
    op.create_index(op.f('ix_invitations_society_id'), 'invitations', ['society_id'], unique=False)
    op.create_index(op.f('ix_invitations_unit_id'), 'invitations', ['unit_id'], unique=False)
    op.create_table('memberships',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('unit_id', sa.String(length=36), nullable=False),
    sa.Column('society_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("role IN ('Owner', 'Tenant', 'Family Member')"),
    sa.ForeignKeyConstraint(['society_id'], ['societies.id'], ),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'unit_id')
    )
    op.create_index(op.f('ix_memberships_society_id'), 'memberships', ['society_id'], unique=False)
    op.create_index(op.f('ix_memberships_unit_id'), 'memberships', ['unit_id'], unique=False)
    op.create_index(op.f('ix_memberships_user_id'), 'memberships', ['user_id'], unique=False)
    op.create_table('uploads',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('filename', sa.String(length=200), nullable=False),
    sa.Column('key', sa.String(length=300), nullable=False),
    sa.Column('content_type', sa.String(length=80), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('unit_id', sa.String(length=36), nullable=False),
    sa.Column('society_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['society_id'], ['societies.id'], ),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_index(op.f('ix_uploads_society_id'), 'uploads', ['society_id'], unique=False)
    op.create_index(op.f('ix_uploads_unit_id'), 'uploads', ['unit_id'], unique=False)
    op.create_table('vehicles',
    sa.Column('kind', sa.String(length=10), nullable=False),
    sa.Column('registration', sa.String(length=20), nullable=False),
    sa.Column('manufacturer', sa.String(length=50), nullable=False),
    sa.Column('model', sa.String(length=50), nullable=False),
    sa.Column('color', sa.String(length=30), nullable=False),
    sa.Column('parking_slot', sa.String(length=30), nullable=False),
    sa.Column('unit_id', sa.String(length=36), nullable=False),
    sa.Column('society_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['society_id'], ['societies.id'], ),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('society_id', 'registration')
    )
    op.create_index(op.f('ix_vehicles_society_id'), 'vehicles', ['society_id'], unique=False)
    op.create_index(op.f('ix_vehicles_unit_id'), 'vehicles', ['unit_id'], unique=False)
    op.create_table('visitors',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=16), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('gate', sa.String(length=80), nullable=False),
    sa.Column('purpose', sa.String(length=200), nullable=False),
    sa.Column('vehicle_number', sa.String(length=20), nullable=False),
    sa.Column('photo_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('arrived_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('entry_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('exit_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('unit_id', sa.String(length=36), nullable=False),
    sa.Column('society_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['society_id'], ['societies.id'], ),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_visitors_society_id'), 'visitors', ['society_id'], unique=False)
    op.create_index(op.f('ix_visitors_unit_id'), 'visitors', ['unit_id'], unique=False)
    op.create_table('bill_items',
    sa.Column('bill_id', sa.String(length=36), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['bill_id'], ['bills.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bill_items_bill_id'), 'bill_items', ['bill_id'], unique=False)
    op.create_table('complaint_comments',
    sa.Column('complaint_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['complaint_id'], ['complaints.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_complaint_comments_complaint_id'), 'complaint_comments', ['complaint_id'], unique=False)
    op.create_table('help_visits',
    sa.Column('help_id', sa.String(length=36), nullable=False),
    sa.Column('entry_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('exit_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['help_id'], ['domestic_help.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_help_visits_help_id'), 'help_visits', ['help_id'], unique=False)
    op.create_table('payments',
    sa.Column('bill_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('method', sa.String(length=40), nullable=False),
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.Column('order_id', sa.String(length=100), nullable=True),
    sa.Column('reference', sa.String(length=100), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('unit_id', sa.String(length=36), nullable=False),
    sa.Column('society_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('amount > 0'),
    sa.ForeignKeyConstraint(['bill_id'], ['bills.id'], ),
    sa.ForeignKeyConstraint(['society_id'], ['societies.id'], ),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_id'),
    sa.UniqueConstraint('reference')
    )
    op.create_index(op.f('ix_payments_bill_id'), 'payments', ['bill_id'], unique=False)
    op.create_index(op.f('ix_payments_society_id'), 'payments', ['society_id'], unique=False)
    op.create_index(op.f('ix_payments_unit_id'), 'payments', ['unit_id'], unique=False)
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payments_unit_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_society_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_bill_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_help_visits_help_id'), table_name='help_visits')
    op.drop_table('help_visits')
    op.drop_index(op.f('ix_complaint_comments_complaint_id'), table_name='complaint_comments')
    op.drop_table('complaint_comments')
    op.drop_index(op.f('ix_bill_items_bill_id'), table_name='bill_items')
    op.drop_table('bill_items')
    op.drop_index(op.f('ix_visitors_unit_id'), table_name='visitors')
    op.drop_index(op.f('ix_visitors_society_id'), table_name='visitors')
    op.drop_table('visitors')
    op.drop_index(op.f('ix_vehicles_unit_id'), table_name='vehicles')
    op.drop_index(op.f('ix_vehicles_society_id'), table_name='vehicles')
    op.drop_table('vehicles')
    op.drop_index(op.f('ix_uploads_unit_id'), table_name='uploads')
    op.drop_index(op.f('ix_uploads_society_id'), table_name='uploads')
    op.drop_table('uploads')
    op.drop_index(op.f('ix_memberships_user_id'), table_name='memberships')
    op.drop_index(op.f('ix_memberships_unit_id'), table_name='memberships')
    op.drop_index(op.f('ix_memberships_society_id'), table_name='memberships')
    op.drop_table('memberships')
    op.drop_index(op.f('ix_invitations_unit_id'), table_name='invitations')
    op.drop_index(op.f('ix_invitations_society_id'), table_name='invitations')
    op.drop_table('invitations')
    op.drop_index(op.f('ix_family_members_unit_id'), table_name='family_members')
    op.drop_index(op.f('ix_family_members_society_id'), table_name='family_members')
    op.drop_table('family_members')
    op.drop_index(op.f('ix_emergency_alerts_unit_id'), table_name='emergency_alerts')
    op.drop_index(op.f('ix_emergency_alerts_society_id'), table_name='emergency_alerts')
    op.drop_table('emergency_alerts')
    op.drop_index(op.f('ix_domestic_help_unit_id'), table_name='domestic_help')
    op.drop_index(op.f('ix_domestic_help_society_id'), table_name='domestic_help')
    op.drop_table('domestic_help')
    op.drop_index(op.f('ix_complaints_unit_id'), table_name='complaints')
    op.drop_index(op.f('ix_complaints_society_id'), table_name='complaints')
    op.drop_table('complaints')
    op.drop_index(op.f('ix_bookings_unit_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_society_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_amenity_id'), table_name='bookings')
    op.drop_index('ix_booking_overlap', table_name='bookings')
    op.drop_table('bookings')
    op.drop_index(op.f('ix_bills_unit_id'), table_name='bills')
    op.drop_index(op.f('ix_bills_society_id'), table_name='bills')
    op.drop_table('bills')
    op.drop_index(op.f('ix_units_society_id'), table_name='units')
    op.drop_table('units')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_family'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_society_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_notices_society_id'), table_name='notices')
    op.drop_table('notices')
    op.drop_index(op.f('ix_documents_society_id'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_directory_society_id'), table_name='directory')
    op.drop_table('directory')
    op.drop_index(op.f('ix_devices_user_id'), table_name='devices')
    op.drop_table('devices')
    op.drop_index(op.f('ix_buildings_society_id'), table_name='buildings')
    op.drop_table('buildings')
    op.drop_index(op.f('ix_amenities_society_id'), table_name='amenities')
    op.drop_table('amenities')
    op.drop_table('users')
    op.drop_table('societies')
    op.drop_table('rate_limits')
    op.drop_index(op.f('ix_otp_challenges_phone'), table_name='otp_challenges')
    op.drop_table('otp_challenges')
    # ### end Alembic commands ###
