"""community_operations"""
from alembic import op
import sqlalchemy as sa

revision = 'fcedebb98a6f'
down_revision = 'e4ec22c2fe06'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assets',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('notes', sa.String(length=2000), nullable=False),
    sa.Column('next_service_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_service_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('society_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['society_id'], ['societies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assets_society_id'), 'assets', ['society_id'], unique=False)
    op.create_table('meetings',
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('agenda', sa.Text(), nullable=False),
    sa.Column('minutes', sa.Text(), nullable=False),
    sa.Column('society_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['society_id'], ['societies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meetings_society_id'), 'meetings', ['society_id'], unique=False)
    op.create_table('platform_subscriptions',
    sa.Column('plan', sa.String(length=60), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('renews_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('society_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['society_id'], ['societies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('society_id')
    )
    op.create_index(op.f('ix_platform_subscriptions_society_id'), 'platform_subscriptions', ['society_id'], unique=False)
    op.create_table('polls',
    sa.Column('question', sa.String(length=300), nullable=False),
    sa.Column('options', sa.JSON(), nullable=False),
    sa.Column('closes_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('society_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['society_id'], ['societies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_polls_society_id'), 'polls', ['society_id'], unique=False)
    op.create_table('privacy_requests',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('details', sa.String(length=2000), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('response', sa.String(length=2000), nullable=False),
    sa.Column('society_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['society_id'], ['societies.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_privacy_requests_society_id'), 'privacy_requests', ['society_id'], unique=False)
    op.create_table('poll_votes',
    sa.Column('poll_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('option', sa.Integer(), nullable=False),
    sa.Column('unit_id', sa.String(length=36), nullable=False),
    sa.Column('society_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['poll_id'], ['polls.id'], ),
    sa.ForeignKeyConstraint(['society_id'], ['societies.id'], ),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('poll_id', 'unit_id')
    )
    op.create_index(op.f('ix_poll_votes_society_id'), 'poll_votes', ['society_id'], unique=False)
    op.create_index(op.f('ix_poll_votes_unit_id'), 'poll_votes', ['unit_id'], unique=False)
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_poll_votes_unit_id'), table_name='poll_votes')
    op.drop_index(op.f('ix_poll_votes_society_id'), table_name='poll_votes')
    op.drop_table('poll_votes')
    op.drop_index(op.f('ix_privacy_requests_society_id'), table_name='privacy_requests')
    op.drop_table('privacy_requests')
    op.drop_index(op.f('ix_polls_society_id'), table_name='polls')
    op.drop_table('polls')
    op.drop_index(op.f('ix_platform_subscriptions_society_id'), table_name='platform_subscriptions')
    op.drop_table('platform_subscriptions')
    op.drop_index(op.f('ix_meetings_society_id'), table_name='meetings')
    op.drop_table('meetings')
    op.drop_index(op.f('ix_assets_society_id'), table_name='assets')
    op.drop_table('assets')
    # ### end Alembic commands ###
